### ISSUE TITLE
关于集合weibo_follow.py的一些疑问

### ISSUE THREAD

**Issue by LinJiowo** [Artificialimbecile/WeiboSpider#14]
大佬，这个项目的weibo_follow.py里，“获取列表关注页数”的get_page_num函数里，比您给出的链接里，多了user_name = selector.xpath('//div[@class="ut"]/text()')[0]  和 user_name = user_name[:user_name.find('关注')]  # 获取user_name 内容，请问这两行代码是如何从ut元素获取到user_name的内容呢？

**Comment by Artificialimbecile** [comment]
第一个user_name获取的内容是“某某关注的人”，第二个user_name截取“关注”之前的字符，就是“某某”，这两行代码只是获取输入uid的昵称，并让这个昵称位于关注列表follow_name_list的第0位，方便draw.py绘制关系图。

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
fajketpdl, @youtube-jocoding, @chenhui0212, @gxian, @denvera, @blaketech-mjb, @ibaddesmukh, @puhsu, @takato86, @rjoshima, @tinykishore, @fostiropoulos, @alimoezzi, @treeoflovely, @NikhilSKashyap, @jwbargsten, @junyuanjyjy, @Kye256, @twilwa, @patraanjan23

**Comment by LinJiowo** [comment]
> 第一个user_name获取的内容是“某某关注的人”，第二个user_name截取“关注”之前的字符，就是“某某”，这两行代码只是获取输入uid的昵称，并让这个昵称位于关注列表follow_name_list的第0位，方便draw.py绘制关系图。

明白了，谢谢大佬解惑！
